# Generated by Django 4.2.13 on 2024-06-21 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_detalleventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='perfil_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='CategoriaUsuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
