# Generated by Django 4.2.13 on 2024-06-21 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_usuario_groups_remove_usuario_perfil_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
