# Generated by Django 4.2.13 on 2024-06-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_detalleventa_producto'),
        ('core', '0005_remove_venta_usuario_delete_detalleventa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precioproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='PrecioProducto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
