# Generated by Django 4.2.13 on 2024-06-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_detalleventa_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='transaction_date',
            field=models.DateTimeField(),
        ),
    ]
